const D=window.FAMILY_DATA, P=Object.fromEntries(D.people.map(p=>[p.id,p])), S=Object.fromEntries(D.sources.map(s=>[s.id,s]));
const el=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected='edmond',zoom=.65,current='main',pos={},size=[1700,1340],listMode=window.matchMedia('(max-width:900px)').matches,lastFocus=null; const mobile=()=>window.matchMedia('(max-width:900px)').matches;
const layouts={main:{size:[1700,1340],pos:{jacques:[170,25],justine:[450,25],jean:[1320,25],andre1827:[40,280],camille:[320,280],jules:[1000,280],adelphine:[1280,280],fernand:[40,540],anna:[320,540],edmond:[1000,540],yvonne:[1280,540],maurice:[20,830],juliette:[280,830],andre1901:[580,830],colette:[840,830],germaine:[1140,830],pierre:[1400,830],alain:[300,1110],brigitte:[580,1110],philippe:[860,1110]}},desc:{size:[1700,740],pos:{edmond:[700,25],yvonne:[960,25],maurice:[20,310],juliette:[280,310],andre1901:[580,310],colette:[840,310],germaine:[1140,310],pierre:[1400,310],alain:[300,570],brigitte:[580,570],philippe:[860,570]}},pecquet:{size:[1050,700],pos:{pecquet:[240,30],dumont:[520,30],andre1901:[240,300],colette:[520,300],philippe:[240,570]}},corsi:{size:[1050,540],pos:{homere:[240,30],celine:[520,30],maurice:[240,300],juliette:[520,300]}},preaudat:{size:[1050,540],pos:{emile:[240,30],blanche:[520,30],germaine:[240,300],pierre:[520,300]}}};

Object.assign(layouts,{"ancestors": {"size": [1560, 1500], "pos": {"jeans": [40, 30], "laplante": [320, 30], "saclierpere": [1080, 30], "lazare": [320, 310], "antoinette": [600, 310], "claude": [320, 590], "delorme": [600, 590], "andre1827": [320, 870], "camille": [600, 870], "toussaint": [1160, 870], "edmond": [200, 1150], "fernand": [650, 1150]}}, "deherpe": {"size": [1900, 1790], "pos": {"simon": [350, 30], "adelaide": [650, 30], "athanase": [500, 310], "louise": [800, 310], "sophie": [1380, 310], "julesd": [500, 590], "drin": [800, 590], "pauld": [1380, 590], "eugene": [500, 870], "laure": [800, 870], "louisj": [1380, 870], "pecquet": [500, 1150], "dumont": [800, 1150], "andre1901": [500, 1430], "colette": [800, 1430]}}, "dumont": {"size": [1100, 1250], "pos": {"gustave": [200, 30], "gaget": [500, 30], "eugene": [200, 310], "laure": [500, 310], "pecquet": [200, 590], "dumont": [500, 590], "andre1901": [200, 870], "colette": [500, 870]}}, "pecquet": {"size": [1400, 1250], "pos": {"leonce": [200, 30], "mansion": [500, 30], "pecquet": [200, 310], "dumont": [500, 310], "andre1901": [200, 590], "colette": [500, 590], "alain": [50, 870], "brigitte": [350, 870], "philippe": [650, 870]}}, "alliance1930": {"size": [1560, 780], "pos": {"leonce": [30, 30], "mansion": [330, 30], "samuel": [850, 30], "hinde": [1150, 30], "pecquet": [330, 310], "eugenie": [850, 310], "morel": [1150, 590]}}});
layouts.ancestors.size=[1700,1500];layouts.ancestors.pos.toussaint=[1080,870];layouts.ancestors.pos.appoline=[1360,870];

function labelDate(e){return e.date||'date à compléter'}
function buttons(ids){return ids.map(id=>`<button class="mini" data-source="${id}">${id}</button>`).join('')}
function badge(status){return `<span class="badge ${['À confirmer','Borne documentaire','Table'].includes(status)?'warn':''}">${esc(status)}</span>`}
function eventHTML(title,e){return `<div class="fact"><small>${title}</small><strong>${esc(e.date||'Date à compléter')}</strong><div>${esc(e.place||'Lieu à compléter')}</div>${e.detail?`<p>${esc(e.detail)}</p>`:''}${e.sources.length?badge(e.status)+buttons(e.sources):'<span class="badge warn">Non renseigné</span>'}</div>`}
function detail(id){selected=id;const p=P[id];let h=`<button class="sheet-close" id="sheet-close" aria-label="Fermer la fiche">Fermer ✕</button><div class="eyebrow">${esc(p.branch)} · fiche individuelle</div><h2>${esc(p.name)}</h2>${p.occupation?`<p class="small">${esc(p.occupation)}</p>`:''}`+eventHTML('Naissance',p.birth);
let us=D.unions.filter(u=>u.a===id||u.b===id);us.forEach(u=>{let sp=P[u.a===id?u.b:u.a];h+=`<div class="fact"><small>Mariage</small><strong>${esc(u.date||'Date à compléter')}</strong><div>${esc(u.place||'Lieu à compléter')}</div><p>Avec <button class="mini" data-person="${sp.id}">${esc(sp.name)}</button></p>${u.note?`<p>${esc(u.note)}</p>`:''}${u.sources.length?badge(u.date?u.status:'Date inconnue')+buttons(u.sources):''}</div>`});if(!us.length)h+='<div class="fact"><small>Mariage</small><div>Non renseigné dans le dossier</div></div>';h+=eventHTML('Décès',p.death);
if(p.parents.length)h+=`<div class="fact"><small>Parents — voir les sources</small>${p.parents.map(v=>`<button class="mini" data-person="${v}">${esc(P[v].name)}</button>`).join('')}${id==='adelphine'?'<p>Lien avec Jean Nachon à confirmer.</p>':''}</div>`;
let children=D.people.filter(q=>q.parents.includes(id));if(children.length)h+=`<div class="fact"><small>Enfants présents dans le dossier</small>${children.map(q=>`<button class="mini" data-person="${q.id}">${esc(q.name)}</button>`).join('')}</div>`;
if(p.relations?.length)h+=`<div class="fact"><small>Autres liens attestés</small>${p.relations.map(r=>`<p>${esc(r.label)} : <button class="mini" data-person="${r.target}">${esc(P[r.target].name)}</button></p>`).join('')}</div>`;if(p.notes)h+=`<div class="note">${esc(p.notes)}</div>`;h+='<div class="fact"><small>Pièces associées</small>'+p.sources.map(s=>`<button class="doclink" data-source="${s}">${s} · ${esc(S[s].title)}</button>`).join('')+'</div>';el('detail').innerHTML=h;document.querySelectorAll('.person,.list-person').forEach(b=>b.classList.toggle('selected',b.dataset.person===id));el('sheet-close').onclick=closeSheet;}
function draw(){const notes={deherpe:'Louise et Sophie Rosé : deux lectures différentes des actes, identité à vérifier. Louis Joseph est un petit-fils dont les parents restent inconnus.',ancestors:'Claude : naissance au 22 décembre 1788 dans le baptême, au 20 décembre dans le décès. Toussaint (1819-1890), frère d’André, est désormais rattaché à Claude Sauvageot et Marie Delorme ; son épouse Appoline Courioux est attestée par son décès.',alliance1930:'Maurice Pecquet épouse Eugénie Moskowits en 1930 après son divorce de Suzanne Dumont. Henri Morel est le précédent époux d’Eugénie.'};el('branch-note').textContent=notes[current]||'';el('branch-note').classList.toggle('hidden',!notes[current]);pos=layouts[current].pos;size=layouts[current].size;let paths='',labels='',cards='';const path=(d,color='#71958a',dash='')=>`<path d="${d}" fill="none" stroke="${color}" stroke-width="2" ${dash?'stroke-dasharray="7 5"':''}/>`;
D.unions.forEach(u=>{if(!pos[u.a]||!pos[u.b])return;let a=pos[u.a],b=pos[u.b];if(a[1]!==b[1])return;let left=a[0]<b[0]?a:b,right=a[0]<b[0]?b:a,cx=(left[0]+240+right[0])/2,y=a[1];paths+=path(`M${left[0]+240},${y+78}H${right[0]}`,'#b08d51');if(u.date){labels+=`<div class="union" style="left:${cx-110}px;top:${y+173}px">${esc(u.date)} · ${esc(u.place.replace(/ \(.*/,''))}${u.status==='À confirmer'?' ?':''}</div>`;paths+=path(`M${cx},${y+78}V${y+173}`,'#b08d51')}
});
const groups={};Object.keys(pos).forEach(id=>{let pars=P[id].parents.filter(v=>pos[v]);if(pars.length){let key=pars.join('|');(groups[key]??=[]).push(id)}});Object.entries(groups).forEach(([key,kids])=>{let ps=key.split('|'),a=pos[ps[0]],sx=a[0]+120,sy=a[1]+155;if(ps.length===2&&pos[ps[1]][1]===a[1]){let b=pos[ps[1]];let u=D.unions.find(u=>ps.includes(u.a)&&ps.includes(u.b));if(!u){let yy=Math.min(...kids.map(k=>pos[k][1]))-35;ps.forEach(v=>{let xy=pos[v];paths+=path(`M${xy[0]+120},${xy[1]+155}V${yy}H${pos[kids[0]][0]+120}`)});kids.forEach(k=>paths+=path(`M${pos[kids[0]][0]+120},${yy}H${pos[k][0]+120}V${pos[k][1]}`));return;}sx=(a[0]+b[0]+240)/2;sy=a[1]+78;if(u?.date)sy=a[1]+211;}let ky=Math.min(...kids.map(k=>pos[k][1]));let by=sy+(ky-sy)*(ps.includes('jules')?.28:.72);let color=ps.includes('jules')?'#b08d51':'#71958a';let dash=key==='jean'||kids.some(k=>P[k].uncertainParents);paths+=path(`M${sx},${sy}V${by}`,color,dash);kids.forEach(id=>{let k=pos[id];paths+=path(`M${sx},${by}H${k[0]+120}V${k[1]}`,color,dash)})});
Object.entries(pos).forEach(([id,[x,y]])=>{let p=P[id],fam=p.name.split(' ').slice(-1)[0];cards+=`<button class="person ${p.branch.toLowerCase()} ${id===selected?'selected':''}" data-person="${id}" style="left:${x}px;top:${y}px"><div class="family">${esc(fam)}</div><div class="given">${esc(p.short)}</div><div class="life"><div><span>°</span>${esc(p.birth.date||'Naissance à compléter')}</div><div>${esc(p.birth.place||'')}</div><div><span>†</span>${esc(p.death.date||'Décès non renseigné')}</div></div><div class="more">${p.sources.length} pièce${p.sources.length>1?'s':''} · ouvrir la fiche →</div></button>`});
el('tree').style.width=size[0]+'px';el('tree').style.height=size[1]+'px';el('tree').innerHTML=`<svg width="${size[0]}" height="${size[1]}" aria-hidden="true">${paths}</svg>${labels}${cards}`;applyZoom();renderList();setMode();filter();}
function applyZoom(){el('tree').style.transform=`scale(${zoom})`;el('space').style.width=size[0]*zoom+'px';el('space').style.height=size[1]*zoom+'px';el('scale').textContent=Math.round(zoom*100)+' %'}
function fit(){zoom=Math.min(1,Math.max(.18,(el('viewport').clientWidth-30)/size[0]));applyZoom()}
function showPerson(id){if(!pos[id]){current=Object.keys(layouts).find(k=>layouts[k].pos[id])||'main';el('view').value=current;draw();fit()}showTab('arbre');detail(id);let p=pos[id];el('viewport').scrollTo({left:Math.max(0,p[0]*zoom-el('viewport').clientWidth/3),top:Math.max(0,p[1]*zoom-50)});if(mobile())openSheet();}
function filter(){let q=el('search').value.toLocaleLowerCase('fr');document.querySelectorAll('.person,.list-person').forEach(b=>b.classList.toggle('dim',q&&!P[b.dataset.person].name.toLocaleLowerCase('fr').includes(q)))}
function showTab(id){['arbre','actes','carte','recherche'].forEach(v=>el(v).classList.toggle('hidden',v!==id));document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===id))}
function source(id){let s=S[id];el('mtitle').textContent=id+' · '+s.title;el('mbody').innerHTML=`<p>${esc(s.ref)}</p><p class="small">Provenance : ${esc(s.file)}</p>${s.url?`<a class="button" href="${esc(s.url)}" target="_blank" rel="noopener">Ouvrir le registre ↗</a>`:'<span class="badge warn">Lien fiable vers ce registre à compléter</span>'}${s.note?`<div class="note">${esc(s.note)}</div>`:''}${s.image?`<p class="small">Cliquer sur une image pour passer à sa taille originale.</p>${(s.images||[s.image]).map((im,i)=>`<div class="scanzoom" style="margin-bottom:16px"><img class="scan" src="${im}" alt="${esc(s.title)} — capture ${i+1}"></div>`).join('')}`:'<div class="issue">Aucune image jointe pour cette pièce.</div>'}${s.transcription?`<details><summary>${esc(s.transLabel||'Lire la transcription du dossier')}</summary><p class="small">Relevé ou transcription de travail ; consulter les réserves et la capture originale.</p><div class="trans">${esc(s.transcription)}</div></details>`:''}`;el('modal').showModal();}
el('gallery').innerHTML=D.sources.map(s=>`<button class="doccard" data-source="${s.id}">${s.image?`<img src="${s.image}" loading="lazy" alt="${esc(s.title)}">`:'<div class="noimage">Transcription ou renseignement</div>'}<div class="content"><div class="eyebrow">${s.id} · ${esc(s.kind)}</div><h3>${esc(s.title)}</h3><p>${esc(s.ref)}</p><p class="small">Provenance : ${esc(s.file)}</p></div></button>`).join('');el('issues').innerHTML=D.issues.map((s,i)=>`<div class="issue"><span class="eyebrow">Point ${i+1}</span><p>${esc(s)}</p></div>`).join('');el('index').innerHTML=D.people.map(p=>`<button data-person="${p.id}">${esc(p.name)}</button>`).join('');
document.addEventListener('click',e=>{let b=e.target.closest('[data-person]');if(b)showPerson(b.dataset.person);let s=e.target.closest('[data-source]');if(s)source(s.dataset.source);let t=e.target.closest('[data-tab]');if(t)showTab(t.dataset.tab);if(e.target.classList.contains('scan'))e.target.parentElement.classList.toggle('expanded')});el('close').onclick=()=>el('modal').close();el('view').onchange=e=>{current=e.target.value;if(!layouts[current].pos[selected])selected=Object.keys(layouts[current].pos)[0];draw();detail(selected);fit();el('viewport').scrollTo(0,0)};el('plus').onclick=()=>{zoom=Math.min(1.6,zoom+.15);applyZoom()};el('minus').onclick=()=>{zoom=Math.max(.18,zoom-.15);applyZoom()};el('fit').onclick=fit;el('search').oninput=filter;el('search').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();let q=e.target.value.toLowerCase(),p=D.people.find(p=>p.name.toLowerCase().includes(q));if(p)showPerson(p.id)}};el('export').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(D,null,2)],{type:'application/json'}));a.download='Sauvageot_donnees_genealogiques.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
function renderList(){const groups={};Object.entries(pos).forEach(([id,xy])=>(groups[xy[1]]??=[]).push(id));let h='';Object.keys(groups).sort((a,b)=>a-b).forEach((y,i)=>{h+=`<section class="generation"><h3>Génération ${i+1} · ${i===0?'les ascendants':'la descendance'}</h3><div class="generation-grid">`;groups[y].forEach(id=>{let p=P[id],u=D.unions.find(u=>u.a===id||u.b===id),sp=u?P[u.a===id?u.b:u.a]:null;h+=`<button class="list-person ${p.branch.toLowerCase()} ${id===selected?'selected':''}" data-person="${id}"><div class="family">${esc(p.branch)}</div><div class="given">${esc(p.name)}</div><div class="life">° ${esc(p.birth.date||'Naissance à compléter')}${p.birth.place?' · '+esc(p.birth.place):''}<br>† ${esc(p.death.date||'Décès non renseigné')}${p.death.place?' · '+esc(p.death.place):''}</div><div class="relation">${p.parents.length?'Parents : '+p.parents.map(v=>esc(P[v].name)).join(' et ')+'.<br>':''}${sp?'Avec '+esc(sp.name)+(u.date?' · '+esc(u.date):'')+'.<br>':''}${p.sources.length} pièce(s) · Ouvrir la fiche →</div></button>`});h+='</div></section>'});el('family-list').innerHTML=h}
function setMode(){el('family-list').classList.toggle('hidden',!listMode);el('viewport').classList.toggle('hidden',listMode);el('mode').textContent=listMode?'Vue arbre':'Vue liste';el('mode').setAttribute('aria-pressed',String(listMode));['minus','plus','fit','scale'].forEach(id=>el(id).classList.toggle('hidden',listMode));}
function lockBehind(v){document.querySelectorAll('header,nav,.stage,#actes,#carte,#recherche,footer').forEach(n=>n.inert=v)}
function openSheet(){lastFocus=document.activeElement;document.body.classList.add('detail-open');el('detail').setAttribute('role','dialog');el('detail').setAttribute('aria-modal','true');el('detail').setAttribute('aria-label','Fiche de '+P[selected].name);lockBehind(true);el('detail').scrollTop=0;el('sheet-close').focus()}
function closeSheet(){document.body.classList.remove('detail-open');el('detail').removeAttribute('role');el('detail').removeAttribute('aria-modal');lockBehind(false);if(lastFocus?.isConnected)lastFocus.focus()}
el('sheet-backdrop').onclick=closeSheet;el('mode').onclick=()=>{listMode=!listMode;setMode();if(!listMode)fit()};
document.addEventListener('keydown',e=>{if(!document.body.classList.contains('detail-open')||el('modal').open)return;if(e.key==='Escape')closeSheet();if(e.key==='Tab'){let a=[...el('detail').querySelectorAll('button,a[href],input')].filter(n=>n.offsetParent!==null);if(e.shiftKey&&document.activeElement===a[0]){e.preventDefault();a.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===a.at(-1)){e.preventDefault();a[0].focus()}}});
window.addEventListener('resize',()=>{if(!mobile())closeSheet();if(!listMode)fit()});
draw();if(!listMode)fit();detail(selected);
