(()=>{
const rows=window.ADDRESS_DATA||[], family=window.FAMILY_DATA||{people:[]};
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\([^)]*\)/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const people=family.people||[];
function branches(row){const out=new Set();String(row['Personnes liées']||'').split(';').forEach(raw=>{const n=norm(raw);let p=people.find(p=>{let pn=norm(p.name);return pn===n||pn.includes(n)||n.includes(pn)});if(p?.branch)out.add(p.branch)});return [...out]}
rows.forEach((r,i)=>{r._id=i;r._branches=branches(r);r._search=norm([r['Nom du point'],r['Adresse Google Maps'],r['Personnes liées'],r['Date / période'],r['Notes']].join(' '))});
let map=null, layer=null, initialized=false, markers=new Map(), visibleRows=rows.slice(), geocoding=false;
const cacheKey='sauvageot-geocode-v2';let cache={};try{cache=JSON.parse(localStorage.getItem(cacheKey)||'{}')}catch(e){}
const saveCache=()=>{try{localStorage.setItem(cacheKey,JSON.stringify(cache))}catch(e){}};
function mapLink(r){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(r['Adresse Google Maps'])}
function popup(r){return `<div class="map-popup"><h3>${esc(r['Nom du point'])}</h3><p><strong>${esc(r['Personnes liées'])}</strong></p><p>${esc(r['Type de lien'])}${r['Date / période']?' · '+esc(r['Date / période']):''}</p>${r['Notes']?`<p>${esc(r['Notes'])}</p>`:''}<p class="small">${esc(r['Source'])}</p><div class="map-actions"><a href="${mapLink(r)}" target="_blank" rel="noopener">Google Maps ↗</a>${r['Lien archive']?`<a href="${esc(r['Lien archive'])}" target="_blank" rel="noopener">Voir l’acte ↗</a>`:''}</div></div>`}
function markerStyle(r){return r['Groupe']==='Famille'?{radius:7,weight:2,fillOpacity:.88}:{radius:6,weight:2,fillOpacity:.72}}
function addMarker(r,loc){if(!map||!loc)return;const m=L.circleMarker([loc.lat,loc.lon],markerStyle(r)).bindPopup(popup(r));m.on('click',()=>highlight(r._id));markers.set(r._id,m);if(isVisible(r))m.addTo(layer)}
function isVisible(r){return visibleRows.some(v=>v._id===r._id)}
function highlight(id){document.querySelectorAll('.map-place').forEach(b=>b.classList.toggle('selected',Number(b.dataset.id)===id));const b=document.querySelector(`.map-place[data-id="${id}"]`);b?.scrollIntoView({block:'nearest'})}
function renderList(){const box=$('map-list');if(!box)return;box.innerHTML=visibleRows.length?visibleRows.map(r=>`<button class="map-place" data-id="${r._id}"><strong>${esc(r['Nom du point'])}</strong><span>${esc(r['Type de lien'])}${r['Date / période']?' · '+esc(r['Date / période']):''}</span><span class="map-people">${esc(r['Personnes liées'])}</span></button>`).join(''):'<div class="map-empty">Aucune adresse pour ces filtres.</div>'}
function filter(){const br=$('map-branch')?.value||'',grp=$('map-group')?.value||'',q=norm($('map-search')?.value||'');visibleRows=rows.filter(r=>(!br||r._branches.includes(br))&&(!grp||r['Groupe']===grp)&&(!q||r._search.includes(q)));renderList();if(layer){layer.clearLayers();visibleRows.forEach(r=>{const m=markers.get(r._id);if(m)m.addTo(layer)})}}
async function geocodeBAN(address){let u='https://data.geopf.fr/geocodage/search?limit=1&q='+encodeURIComponent(address);let res=await fetch(u);if(!res.ok)throw new Error('BAN '+res.status);let j=await res.json();let f=j.features?.[0];if(!f)return null;let [lon,lat]=f.geometry.coordinates;return {lat,lon,label:f.properties?.label||address,score:f.properties?.score||0,source:'BAN'}}
async function geocodeNominatim(address){let u='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=fr&q='+encodeURIComponent(address);let res=await fetch(u,{headers:{'Accept-Language':'fr'}});if(!res.ok)throw new Error('Nominatim '+res.status);let j=await res.json();if(!j[0])return null;return {lat:+j[0].lat,lon:+j[0].lon,label:j[0].display_name||address,score:null,source:'OSM'}}
async function geocodeRow(r){const key=r['Adresse Google Maps'];if(cache[key])return cache[key].ok===false?null:cache[key];let loc=null;try{loc=await geocodeBAN(key)}catch(e){};if(!loc){await new Promise(x=>setTimeout(x,1050));try{loc=await geocodeNominatim(key)}catch(e){}}cache[key]=loc||{ok:false};saveCache();return loc}
async function geocodeAll(){if(geocoding)return;geocoding=true;let done=0,failed=0;const status=$('map-status');const todo=rows.filter(r=>!markers.has(r._id));for(let i=0;i<todo.length;i+=3){let batch=todo.slice(i,i+3);let vals=await Promise.all(batch.map(async r=>[r,await geocodeRow(r)]));vals.forEach(([r,loc])=>{done++;if(loc)addMarker(r,loc);else failed++});if(status)status.textContent=`Localisation des adresses : ${done}/${todo.length}${failed?` · ${failed} à vérifier`:''}`}
if(status)status.textContent=`${markers.size} adresse${markers.size>1?'s':''} localisée${markers.size>1?'s':''}${failed?` · ${failed} non résolue${failed>1?'s':''}`:''}. Les adresses historiques peuvent nécessiter une vérification.`;fitVisible();geocoding=false}
function fitVisible(){if(!map)return;const pts=visibleRows.map(r=>markers.get(r._id)).filter(Boolean).map(m=>m.getLatLng());if(pts.length)map.fitBounds(L.latLngBounds(pts),{padding:[24,24],maxZoom:16})}
function init(){if(initialized){setTimeout(()=>map.invalidateSize(),50);return}initialized=true;if(!window.L){$('map-status').textContent='La bibliothèque de carte n’a pas pu être chargée. Vérifiez la connexion internet.';return}map=L.map('family-map',{scrollWheelZoom:true}).setView([46.5,2.3],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);layer=L.layerGroup().addTo(map);const branchSel=$('map-branch');[...new Set(rows.flatMap(r=>r._branches))].sort((a,b)=>a.localeCompare(b,'fr')).forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;branchSel.appendChild(o)});renderList();['map-branch','map-group'].forEach(id=>$(id).addEventListener('change',filter));$('map-search').addEventListener('input',filter);$('map-fit').addEventListener('click',fitVisible);$('map-list').addEventListener('click',e=>{let b=e.target.closest('.map-place');if(!b)return;let id=Number(b.dataset.id),m=markers.get(id);if(m){map.setView(m.getLatLng(),16,{animate:true});m.openPopup();highlight(id)}});geocodeAll();setTimeout(()=>map.invalidateSize(),100)}
document.addEventListener('click',e=>{if(e.target.closest('[data-tab="carte"]'))setTimeout(init,20)});
})();
